{% set name = "devpi-common" %}
{% set version = "4.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 235a0a9a45c96e54c60ba6ba2f77d856cf90f1a69c1bee949887e9edc03a41cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - lazy
    - packaging-legacy
    - python >=3.7
    - requests >=2.3.0

test:
  imports:
    - devpi_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/devpi/devpi
  dev_url: https://github.com/devpi/devpi/tree/main/common
  doc_url: http://doc.devpi.net/
  summary: Devpi utilities jointly used by devpi-server and devpi-client
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
