{% set version = "4.1.0" %}

package:
  name: devpi-common
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/devpi-common/devpi-common-{{ version }}.tar.gz
  sha256: 58d7f761e3fe7fdfe449c4a6a9e2350d4ddfbeb66cb0f6d208025142943030d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-changelog-shortener
    - wheel
  run:
    - lazy
    - packaging-legacy
    - python >={{ python_min }}
    - requests >=2.3.0

test:
  imports:
    - devpi_common
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/devpi/devpi
  dev_url: https://github.com/devpi/devpi/tree/main/common
  doc_url: http://doc.devpi.net/
  summary: Devpi utilities jointly used by devpi-server and devpi-client
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
